config/routes.rb
Rails.application.routes.draw do
  resources :prompts, only: [:index]
  root 'prompts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prompt.rb
# app/models/prompt.rb
class Prompt < ApplicationRecord
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
  
    settings index: { number_of_shards: 1 } do
      mappings dynamic: 'false' do
        indexes :content, type: 'text'
      end
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prompts_controller.rb
# app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  def index
    if params[:query].present?
      @prompts = Prompt.search(params[:query]).records
    else
      @prompts = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Madrid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/prompts/index.html.erb
<!-- app/views/prompts/index.html.erb -->
<h1>Prompt Search</h1>

<%= form_tag(prompts_path, method: :get) do %>
  <%= text_field_tag :query, params[:query], placeholder: "Enter words..." %>
  <%= submit_tag "Search" %>
<% end %>

<% if @prompts.any? %>
  <h2>Search Results for: <%= params[:query] %></h2>
  <ul>
    <% @prompts.each do |prompt| %>
      <li><%= prompt.content %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found for: <%= params[:query] %></p>
<% end %>